### ISSUE TITLE
React example?

### ISSUE THREAD

**Issue by PatricioNG** [brianzinn/browserprint-es#1]
Wondering if there's a basic example of how one might print a file to the default device using React? I've been playing around with the interfaces but can't seem to get things in the right place or a file to print.

**Comment by PatricioNG** [comment]
@brianzinn Seems like I was able to get this sorted, only outstanding question now is what is the license key, and how would I obtain one? 

`The format conversion attempted requires a licensing key and none was provided.`

**Comment by brianzinn** [comment]
I think I had that issue once - I was trying to print a PDF.  seems like some devices don't support that.  We got some free printers from FedEx and they didn't work (and also Zebra doesn't support).  I didn't try on some of our more advanced printers.

Can you share what you are trying to convert?  If it's a simple PDF you can use pdf-dist and probably make some ZPL from it.  I've thought actually about making a React renderer for ZPL - I don't think there is one.
https://github.com/brianzinn/browserprint-es/blob/master/src/BrowserPrint.ts#L61

**Comment by brianzinn** [comment]
Another thing you can look at is activating PDF Direct.  I think it works on all newer LinkOS devices.  have a look here:
https://supportcommunity.zebra.com/s/article/PDF-Direct-Activation

Going to close from inactivity, but just re-open if you have more questions - or to post a solution for others, if you find one.  cheers.

**Comment by sushi2all** [comment]
I'll add our experience here. PDF support is baked in by default since firmware (LinkOS) version 6.3, i.e. since about 2018. 

I can easily print PDFs on a TC231 from normal desktop apps, but with BrowserPrint we couldn't get it to work. 

The license key issue arises only when using deprecated methods, but still, I've never been able to get the new ones to work with PDF, only with ZPL and images.
